services:
   db:
     image: postgres
     restart: always
     environment:
        POSTGRES_PASSWORD: sahil
        POSTGRES_USER: myadmin
        POSTGRES_DB: users
     volumes:
       - db_data:/var/lib/postgresql/data
     ports:
      - "5432:5432"
volumes:
  db_data: